### ISSUE TITLE
Photos not displaying

### ISSUE THREAD

**Issue by nicklawson47** [smcaruso/PMIAG3#17]
There are a few instances where the JSON and /pageimages/ file name match up but the image isn't displaying on the page. I'm pretty sure it's a file size issue, and it looks like the cap is around 2MB. Am I correct? I'll resize, if so. Here are some examples:

Ex. #2: ex2_img1_truck.jpg
Ex. #3: ex3_img1_collapsedculvert.jpg, ex3_img3_preparation.jpg
Ex. #4: ex4_img1_installing.jpg, ex4_img2_precast.jpg, ex4_img5_collision.png
Ex. #5: ex5_img1_newlaunchstandard.png, ex5_img4_falcon.jpg
Ex. #6: ex6_img1_ozzie.jpg, ex6_img2_birmingham.jpg, ex6_img4_teamphoto.jpg
Ex. #8: ex8_img1_uhrainbow.jpg
Ex. #9: ex9_img1_mayoepmo.jpg, ex9_img2_bold.jpg, ex9_img3_strategydept.png

**Comment by smcaruso** [comment]
These files aren't in the repo. Are you sure you've pushed them?

There's no file size cap here outside of the git/github limit of 100GB.
