### ISSUE TITLE
Chapter Awards Featured Images & Icons

### ISSUE THREAD

**Issue by nicklawson47** [smcaruso/PMIAG3#20]
I've got them in a folder here: https://drive.google.com/drive/folders/18LM2PGaiGSN0C7UGQ8H7--uRNgj8zu_U

Am I able to upload them or do you need to do that? All of the icons are in a subfolder labeled

**Comment by smcaruso** [comment]
You can upload them in the same place but they need special formatting. Maybe easiest if you can paste them over this screenshot so I know where each goes?
<img width="1452" alt="image" src="https://github.com/smcaruso/PMIAG3/assets/51963719/8e43a18f-ebce-44bf-8eef-0f4fb978c9a6">

Or, you could (have Greg?) make the images with these templates - must be square, 1024 or 2048, images and logos in the orange areas only, black is transparent:
<img width="645" alt="image" src="https://github.com/smcaruso/PMIAG3/assets/51963719/559e3db6-1cc6-4615-ba37-f2e11c608a9d">
<img width="640" alt="image" src="https://github.com/smcaruso/PMIAG3/assets/51963719/3892555b-070e-473d-bf96-b8c3d9c64f45">
<img width="642" alt="image" src="https://github.com/smcaruso/PMIAG3/assets/51963719/1f385f20-5593-4ae2-9184-6a2108f7201a">

**Comment by nicklawson47** [comment]
Hey Steve! I created these as 2048x2048 pngs and published but I'm not seeing anything in the preview space. I'm also not seeing the 3D category names on the walls of the 3D space in the preview, so I'm afraid to make a PR. These 3 images are attached if it makes more sense for you to upload them!
![19](https://github.com/smcaruso/PMIAG3/assets/142542582/eff9d1c9-137e-49ed-8c82-06081f9bdf8c)
![20](https://github.com/smcaruso/PMIAG3/assets/142542582/8bfba484-0715-4605-9ede-574202584df4)
![21](https://github.com/smcaruso/PMIAG3/assets/142542582/e4ad676f-5d00-45e7-9a5e-0daafd150c63)

**Comment by nicklawson47** [comment]
Cloning it to a different place now!

**Comment by nicklawson47** [comment]
I deleted the repo and cloned it to a new folder that isn't linked to iCloud: Users/NickLawson/GitHub/PMIAG3
