### ISSUE TITLE
Mobile landing page/foyer

### ISSUE THREAD

**Issue by nicklawson47** [smcaruso/PMIAG3#29]
Hey Steve — the "swoop in" is looking amazing! I noticed that on mobile/tablet it doesn't have the words appear in the entry portal so that you know to click on the space (since there's no hover).

I'm also having weird things going on in the mobile view which you might already be addressing (sorry if I'm sending this too soon!):
- The landing page has a blank white space at the bottom covering text, and the whole gallery has white space on the sides. 
- The "swoop in" centers on the sign on the left side of the gallery entrance, making it difficult to click on the entrance
- Sometimes when I click on the gallery entrance, I get booted back to the landing page
See below:

![ezgif com-video-to-gif (11)](https://github.com/smcaruso/PMIAG3/assets/142542582/f2803764-08ad-47d9-a4e3-1d628d8f0f86)

**Comment by smcaruso** [comment]
ok I had removed the mobile stylesheet for local testing and  forgot to add it back in! should all be working now.

I did get it to crash once on my phone (15 pro) but not in the simulator, trace showed no errors so my guess is there's a bunk texture somewhere that's bugging out the GPU. I'll look into it more

**Comment by nicklawson47** [comment]
Thanks, Steve! Any luck tracking down that bunk texture? It's important that we figure it out asap. Let me know if there's anything I can do to help!
